### PR TITLE
Fix/locator announcer

### PR DESCRIPTION
**Pull request by antmat**
This PR adds proper locator announcement in case of cluster of hubs.
Also added Members method for cluster for simplicity.

### CODE REVIEW

**Comment by sshaman1101** [comment]
I am trying to build and run it.

When starting hub into a non-failover mode locator will receive zero IP addresses;

line from locator log:
```
2017-11-29T17:44:32.895+0300	INFO	locator/server.go:50	handling Announce request	{"eth": "0x1c54f43a8ec76C15162CC80f31Cf02aE4cd31727", "ips": []}
```

Hub startup log:
```
（╯°□°）╯  sonm-io/core (fix/locator_announcer *%) » ./sonmhub
2017-11-29T17:43:55.834+0300	INFO	hub/server.go:837	registered default worker credentials	{"wallet": "0x1c54f43a8ec76C15162CC80f31Cf02aE4cd31727"}
2017-11-29T17:43:55.834+0300	INFO	hub/cluster.go:496	creating store	{"store": {"Store":{"Type":"boltdb","Endpoint":"/tmp/sonm/boltdb","Bucket":"sonm","KeyFile":"","CertFile":""},"Failover":false,"GrpcEndpoint":"0.0.0.0:10001","LeaderKey":"sonm/hub/leader","MemberListKey":"sonm/hub/list","SynchronizableEntitiesPrefix":"sync_prefix","LeaderTTL":20,"AnnouncePeriod":10,"AnnounceTTL":20,"MemberGCPeriod":60}}
2017-11-29T17:43:55.834+0300	DEBUG	hub/server.go:826	created hub
2017-11-29T17:43:55.835+0300	INFO	hub/server.go:865	listening for connections from Miners	{"address": "[::]:10002"}
2017-11-29T17:43:55.835+0300	INFO	hub/server.go:874	listening for gRPC API connections	{"address": "[::]:10001"}
2017-11-29T17:43:55.835+0300	INFO	hub/cluster.go:566	fetched endpoints of new member	{"endpoints": ["0.0.0.0:10001"]}
2017-11-29T17:43:55.835+0300	INFO	hub/server.go:1106	announcing Hub address	{"eth": "0x1c54f43a8ec76C15162CC80f31Cf02aE4cd31727", "addr": []}
2017-11-29T17:43:55.835+0300	INFO	hub/cluster.go:577	successfully connected to cluster member
2017-11-29T17:43:55.835+0300	INFO	hub/cluster.go:165	runnning in dev single-server mode
2017-11-29T17:43:55.835+0300	INFO	hub/cluster.go:434	subscribing on sync folder
2017/11/29 17:43:55 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: authentication handshake failed: EOF"; Reconnecting to {0.0.0.0:10001 <nil>}
2017/11/29 17:43:56 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: authentication handshake failed: EOF"; Reconnecting to {0.0.0.0:10001 <nil>}
2017/11/29 17:43:58 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: authentication handshake failed: EOF"; Reconnecting to {0.0.0.0:10001 <nil>}
2017/11/29 17:44:01 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: authentication handshake failed: EOF"; Reconnecting to {0.0.0.0:10001 <nil>}
2017/11/29 17:44:05 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: authentication handshake failed: EOF"; Reconnecting to {0.0.0.0:10001 <nil>}
2017/11/29 17:44:12 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: authentication handshake failed: EOF"; Reconnecting to {0.0.0.0:10001 <nil>}
2017/11/29 17:44:22 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: authentication handshake failed: EOF"; Reconnecting to {0.0.0.0:10001 <nil>}
```

**Comment by antmat** [comment]
Looks like a harmless race between cluster.Run and StartLocatorAnnouncer (cause it's repeated by ticker).
Fixed anyway.

**Comment by sshaman1101** [comment]
Non-failover setup is OK. But if you will start a cluster, only the last member's IP will be stored in the locator. 

Got this logs for two Hubs started locally and bound to different endpoints:

```
2017-11-30T12:09:39.292+0300	INFO	locator/server.go:50	handling Announce request	{"eth": "0x1c54f43a8ec76C15162CC80f31Cf02aE4cd31727", "ips": ["192.168.1.77:10001"]}
2017-11-30T12:09:52.898+0300	INFO	locator/server.go:50	handling Announce request	{"eth": "0x1c54f43a8ec76C15162CC80f31Cf02aE4cd31727", "ips": ["192.168.1.77:10010"]}
```

**Comment by antmat** [comment]
What do you suggest? It takes time to join cluster.

**Comment by antmat** [comment]
Anyway it's rather strange - please send me your setup configuration and hub logs

**Comment by antmat** [comment]
got it, fixed

**Pull request merged**
