### PR TITLE
refactor: complete Locator extermination

### PR DESCRIPTION
**Pull request by 3Hren**
Chained with #567, so review it at first.

### CODE REVIEW

**Comment by oopcode** [comment]
dis peeaar is brokken

**Comment by 3Hren** [comment]
```
2018/04/03 18:52:52 failed to import package by path github.com/docker/docker/api/types: cannot find package "github.com/docker/docker/api/types" in any of:
	/home/travis/.gimme/versions/go1.9.4.linux.amd64/src/github.com/docker/docker/api/types (from $GOROOT)
	/home/travis/gopath/src/github.com/docker/docker/api/types (from $GOPATH) - fallback to import path suffix
2018/04/03 18:52:52 imported package collision: "" imported twice
```
I have no idea.

**Comment by 3Hren** [comment]
BTW our master is broken too, but the previous PR have passed (both push and merge commits). Seems like it's Travis having fun again.

**Comment by oopcode** [comment]
true, true

**Pull request merged**
