### PR TITLE
Feature/govendor experiment

### PR DESCRIPTION
**Pull request by sshaman1101**
Fix vendoring, now we must use govendor to manage external libs
successfully build on linux64 and mac os

### CODE REVIEW

**Comment by Sokel** [comment]
`make install` instruction doesn't work

**Comment by sshaman1101** [comment]
@Sokel now `make build && sudo make install` works correctly with typical Linux distro and macOS

**Comment by jorpic** [comment]
**`sudo`**` make install`? rly?
Why not to use `$GOPATH/bin` as a default installation destination instead of `/usr/local/bin`?

**Comment by sshaman1101** [comment]
My mistake, forgot about `$GOPATH/bin`, fixed

**Pull request merged**
